services:
  mongodb:
    build: ./mongodb
    image: priyadaws86/mongodb:v1
    container_name: mongodb
    volumes:
      - mongodb:/data/db

  catalogue:
    build: 
      context: ./catalogue
      dockerfile: Dockerfile
    image: priyadaws86/catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb
  redis:
    image: redis:7.0
    container_name: redis
    volumes:
      - redis:/data
  mysql:
    build: ./mysql
    image: priyadaws86/mysql:v1
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql 
  
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "roboshop"
      RABBITMQ_DEFAULT_PASS: "roboshop123"
    volumes:
      - rabbitmq:/var/lib/rabbitmq
  
  user:
    build: ./user
      context: 
      dockerfile: Dockerfile
    image: priyadaws86/user:v1
    container_name: user
    depends_on:
      - mongodb
      - redis
  cart:
    build: ./cart
    image: priyadaws86/cart:v1
    container_name: cart
    depends_on:
      - redis
      - catalogue
  
  shipping:
    build: ./shipping
    image: priyadaws86/shipping:v1
    container_name: shipping
    depends_on:
      - mysql
      - cart
  
  payment:
    build: ./payment
    image: priyadaws86/payment:v1
    container_name: payment
    depends_on:
      - rabbitmq
      - user
      - cart
  
  frontend:
    build: ./frontend
    image: priyadaws86/frontend:v1
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - catalogue
      - user
      - cart
      - payment
      - shipping

networks:
  default:
    driver: bridge
    name: roboshop
    external: true    #true if you have created the network manually using docker network command

volumes:
  mongodb:
  redis:
  mysql:
  rabbitmq:


